### ISSUE TITLE
onServicesDiscovered An error

### ISSUE THREAD

**Issue by james1106** [sogilis/react-native-bluetooth-manager#3]
undefined is not a function (evaluating 'console.assert("services"in serviceMap||"service"in serviceMap,
                                                          "Missing services in service found event")')

**Comment by graymanto** [comment]
It looks like console.assert isn't supported in android.  The asserts have now been removed from the library.

**Comment by sebn** [comment]
Other relevant commit I can think of:
https://github.com/sogilis/react-native-bluetooth/commit/276aa7fd29104416b40c2f44f348ab814d444a7e
